name = "Blueprint"
author = "ArtificialDan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed6baa881b6be910965d001bbb7bf5d1acd512fed99439e1d342d040b384b1df"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
